services:
  spring-boot:
    image: voting_intention:0.0.1-SNAPSHOT
    container_name: spring-boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/intencaovoto
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=intencaovoto
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
